server:
  port: 8088

spring:
  datasource:
    name: ziroom_t_mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://10.16.16.32:3306/car_sharing?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: dev_rp
      password: ziroomdb
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    jest:
      uris: http://localhost:9200
      read-timeout: 5000
      connection-timeout: 20000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ziroom.model


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.ziroom.dao : DEBUG

swagger:
  show: true

cas:
  url:
   getToken: http://cas.ziroom.com/CAS/api/authentication
   authToken: http://cas.ziroom.com/CAS/api/auth/token


ehr:
  url:
    userDetil:  http://ehrnew.ziroom.com/api/ehr/getUserSimple.action